[MULTI] Apuntes de FR curso 17-18 y enlace a prácticas de IA
DEIIT/Ingenieria-Informatica pull request #23
Opened 2019-10-19 10:20 UTC by patchispatch

No estoy muy seguro de si he puesto bien el enlace a mi repo de IA, si no avisad y lo cambio

2019-10-19 16:00 UTC, advy99 approved these changes

2019-10-19 16:05 UTC, advy99 requested changes
En la parte de IA, lo has puesto en el curso 1617, mientras que el enlace manda a un repo que pone que son prácticas del 1718, ¿podrías arreglarlo?

2019-10-19 16:24 UTC, advy99 commented on 2º 2º cuatrimestre/Inteligencia artificial/curso1718_B/Prácticas/README.md
> +# CURSO 2016-2017
Aquí debería poner curso 2017-2018

2019-10-23 16:31 UTC, advy99 approved these changes

2019-10-23 19:47 UTC, Groctel approved these changes

2019-10-23 19:47 UTC, merged