Añadiendo practicas Calculo
DEIIT/Ingenieria-Informatica pull request #38
Opened 2020-10-10 23:18 UTC by thejosess

He añadido los examenes de las practicas de Calculo de Pilar del año 2019/2020, esta profesora suele repetir tipos de examenes

2020-10-14 23:06 UTC, thejosess commented
¿No veis bien los archivos añadidos?

2020-10-15 08:37 UTC, Groctel requested changes
Hemos tenido unos días movidillos y no hemos tenido tiempo de mirarlo. No admitimos ficheros binarios por facilitar los diff y reducir el tamaño del repositorio. Por favor, sustituye los ficheros `.wxmx` por ficheros de texto plano `.wxm` para los mismos exámenes y aceptaremos la PR.

2020-10-15 08:58 UTC, thejosess commented
Muchas gracias por contestar, no sabía nada de eso. Es que estoy empezando un poco con esto de los pull request :+1:

2020-10-15 17:25 UTC, advy99 approved these changes

2020-10-15 18:14 UTC, Groctel approved these changes

2020-10-15 18:15 UTC, merged